//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollectionWizard.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RoccoSvgIcons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoccoSvgIcons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataCollectionWizard.Client.Resources.RoccoSvgIcons", typeof(RoccoSvgIcons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg viewBox=&quot;0 0 32 32&quot;&gt;&lt;path d=&quot;M16 5c2.139 0 5.25 1.93 5.456 4.58l.049.581c.585 6.619 1.913 7.823 2.98 8.34l.11.05.425.183c.481.215.849.466.97 1.382.322 2.442-7.075 3.608-9.99 3.608l-.273-.003c-3.077-.068-10.03-1.236-9.717-3.605.146-1.108.655-1.244 1.288-1.518l.107-.047.11-.05c1.097-.532 2.472-1.79 3.029-8.92C10.75 6.93 13.86 5 16 5Zm0 1.309c-1.772 0-3.995 1.69-4.127 3.372l-.052.624c-.521 5.92-1.633 8.361-3.734 9.377l-.286.129-.372.157c-.09.043-.065.075-.097.316-.02.151.935.774 2.818 1.291 1.862.512 4.31 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string alarm {
            get {
                return ResourceManager.GetString("alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg viewBox=&quot;0 0 32 32&quot;&gt;&lt;path d=&quot;M12.283 9c4.013 0 5.295 2.091 5.458 2.39l.019.035.039-.011c.47-.135 5.064-1.306 6.742 3.503 0 0 4.459 0 4.459 4.304 0 2.759-1.865 4.442-4.065 4.442H7.455C3.448 22.85 3.02 20.433 3 19.549v-.113c.001-.12.01-.194.012-.211v-.022c-.01-.247-.032-2.922 3.203-3.961C6.216 13.554 7.744 9 12.283 9Zm-1.44 2.116c-1.6 1.117-2.401 2.678-2.401 4.684.001.001.084.002.186.002h.213c.102 0 .183 0 .183-.002-.013 0 0-2.817 2.137-4.057.015.01-.09-.199-.318-.627Z&quot; fill=&quot;#DEDEDE&quot; fill-rule=&quot;evenodd&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cloud_service {
            get {
                return ResourceManager.GetString("cloud_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg viewBox=&quot;0 0 32 32&quot;&gt;&lt;path d=&quot;m15.814 20.81.59 5.115c.212.039.422.115.619.232.92.543 1.232 1.753.696 2.703-.536.949-1.717 1.278-2.637.735-.92-.544-1.232-1.754-.696-2.703.186-.33.45-.585.755-.755l-.578-5.01a5.157 5.157 0 0 0 1.25-.317Zm-9.557-8.193c.303.331.477.744.522 1.169L9 14.33c-.1.424-.155.867-.157 1.324l-2.317-.568.015-.081a1.98 1.98 0 0 1-.326.44 1.827 1.827 0 0 1-2.68-.055c-.73-.795-.71-2.062.041-2.827a1.827 1.827 0 0 1 2.68.054Zm19.397-.888a2.048 2.048 0 0 0-.523 1.168L19 14.33c.1.424.155.867.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cluster {
            get {
                return ResourceManager.GetString("cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg viewBox=&quot;0 0 32 32&quot;&gt;&lt;path d=&quot;M29 13a1 1 0 0 1 1 1v15a1 1 0 0 1-1 1H19a1 1 0 0 1-1-1v-8h11v-3H18v-4a1 1 0 0 1 1-1h10Zm0 13H19v3h10v-3ZM24 4a2 2 0 0 1 2 2v6h-1V6a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v20a1 1 0 0 0 1 1h9v1H8a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h16Zm5 18H19v3h10v-3Zm-3-3.5v2H16v-2h10Zm3-4.5H19v3h10v-3Z&quot; fill=&quot;#DEDEDE&quot; fill-rule=&quot;evenodd&quot;/&gt;&lt;/svg&gt;.
        /// </summary>
        internal static string column_chooser {
            get {
                return ResourceManager.GetString("column_chooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg viewBox=&quot;0 0 24 24&quot;&gt;&lt;path d=&quot;M3.9 14.25v2.25a.6.6 0 0 0 .6.6H9v.9H4.5A1.5 1.5 0 0 1 3 16.5v-2.25h.9Zm17.1 0v2.25a1.5 1.5 0 0 1-1.5 1.5H15v-.9h4.5a.6.6 0 0 0 .6-.6v-2.25h.9Zm-4.22-.762c.311 0 .578.055.8.165.223.11.395.262.517.456.121.194.182.418.182.675 0 .261-.052.502-.155.722-.104.22-.253.438-.45.652l-.038.041h-.973c.115-.121.216-.232.303-.332.155-.177.27-.343.344-.496.075-.153.112-.32.112-.5 0-.22-.063-.385-.19-.495a.731.731 0 0 0-.499-.166c-.202 0-.391.042-.567.125a2.765 2.765 0 0 0-.546.354l-.466-. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string counter {
            get {
                return ResourceManager.GetString("counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg viewBox=&quot;0 0 32 32&quot;&gt;&lt;path d=&quot;M19 7h-5v2.716H9v1.81h15v-1.81h-5V7Zm4.151 5.429L22.2 25.39H10.785L9.833 12.43h13.318Zm-9.268 2.174h-1.032v8.304h1.032v-8.304Zm3.096 0h-1.032v8.304h1.032v-8.304Zm3.096 0h-1.032v8.304h1.032v-8.304Zm-1.908-6.699v1.808h-3.334V7.904h3.334Z&quot; fill=&quot;#DEDEDE&quot; fill-rule=&quot;evenodd&quot;/&gt;&lt;/svg&gt;.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg viewBox=&quot;0 0 32 32&quot;&gt;&lt;path d=&quot;M28 7.5v17H4v-17h24Zm-1 1H5v15h22v-15Zm-5.75 8.917c1.243 0 2.25.951 2.25 2.125 0 1.173-1.007 2.125-2.25 2.125S19 20.715 19 19.542c0-1.174 1.007-2.125 2.25-2.125Zm-7.65-6.73v10.626h-6V10.688h6Zm10.8 0v2.126h-7.2v-2.126h7.2Z&quot; fill=&quot;#DEDEDE&quot; fill-rule=&quot;evenodd&quot;/&gt;&lt;/svg&gt;.
        /// </summary>
        internal static string device {
            get {
                return ResourceManager.GetString("device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg viewBox=&quot;0 0 32 32&quot;&gt;&lt;path d=&quot;m8.334 19.948 3.78 3.668L6 26.062l2.334-6.114ZM18.55 9.335l4.087 4.087-9.275 9.276-4.087-4.088 9.275-9.275ZM21.975 6l.097.004c.434.04.76.33.816.383l2.677 2.676s.89.89 0 1.779l-1.779 1.778-4.446-4.446.659-.66.343-.342.776-.777c.297-.296.593-.395.857-.395Z&quot; fill=&quot;#DEDEDE&quot; fill-rule=&quot;evenodd&quot;/&gt;&lt;/svg&gt;.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg viewBox=&quot;0 0 24 24&quot;&gt;&lt;path d=&quot;M21.75 19.5V21H2.25v-.75h1.5v-.75h18ZM3.846 15.621c.322 0 .583.125.782.375.2.25.3.619.3 1.106 0 .325-.048.599-.142.821-.095.222-.224.39-.389.502a.992.992 0 0 1-.572.168c-.137 0-.255-.018-.354-.053a.859.859 0 0 1-.255-.136 1.273 1.273 0 0 1-.184-.179H2.99a1.903 1.903 0 0 1 .042.42V19.8H2.25v-4.127h.635l.11.373h.037c.053-.077.116-.148.19-.212a.84.84 0 0 1 .264-.155c.104-.039.224-.058.36-.058Zm13.77 2.116c.123 0 .227.032.315.097.087.065.131.177.131.338 0 .154-.044.266-.131.334 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg viewBox=&quot;0 0 24 24&quot;&gt;&lt;path d=&quot;M5.4 3.645a2.07 2.07 0 1 1 2.83 1.926l.006 1.716c0 2.22 1.688 3.998 3.742 3.998 2.809.003 5.062 2.376 5.062 5.278v1.441a2.07 2.07 0 1 1-1.321.062v-1.503c0-2.22-1.688-3.998-3.741-3.998-1.492-.001-2.827-.671-3.751-1.734l.001 7.237a2.07 2.07 0 1 1-1.321-.065V5.637A2.07 2.07 0 0 1 5.4 3.645Zm3.39 16.35a1.32 1.32 0 1 0-2.64 0 1.32 1.32 0 0 0 2.64 0Zm0-16.35a1.32 1.32 0 1 0-2.64 0 1.32 1.32 0 0 0 2.64 0Zm9 16.35a1.32 1.32 0 1 0-2.64 0 1.32 1.32 0 0 0 2.64 0Z&quot; fill=&quot;#DEDEDE&quot; fill- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string recursive {
            get {
                return ResourceManager.GetString("recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg viewBox=&quot;0 0 24 24&quot;&gt;&lt;path d=&quot;M5.239 8.437 7.523 12h-1.6v.178a5.747 5.747 0 0 0 1.737 3.919c1.142 1.113 2.695 1.692 4.203 1.692l.244-.005a5.797 5.797 0 0 0 2.954-.93l.73 1.113a7.335 7.335 0 0 1-3.928 1.158A7.4 7.4 0 0 1 6.7 17.032C5.239 15.652 4.553 13.826 4.553 12H3s2.056-3.25 2.239-3.563Zm6.624-3.562a7.4 7.4 0 0 1 5.162 2.093c1.462 1.38 2.148 3.206 2.148 5.032H21s-2.33 3.25-2.513 3.563L16.203 12h1.599v-.178a5.747 5.747 0 0 0-1.736-3.919c-1.142-1.113-2.695-1.692-4.203-1.692l-.242.005c-.97.038-1.93.303- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg viewBox=&quot;0 0 24 24&quot;&gt;&lt;path d=&quot;m17 3 4 4v12c0 1.1-.9 2-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h12Zm-.311.75H5c-.692 0-1.25.56-1.25 1.25v14c0 .69.558 1.25 1.25 1.25h14c.686 0 1.25-.564 1.25-1.25V7.311L16.689 3.75Zm-4.689 9c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3Zm3-7.5V9H5.25V5.25H15Z&quot; fill=&quot;#DEDEDE&quot; fill-rule=&quot;evenodd&quot;/&gt;&lt;/svg&gt;.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
    }
}
