//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollectionWizard.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SvgIcons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SvgIcons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataCollectionWizard.Client.Resources.SvgIcons", typeof(SvgIcons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 24 24&quot;&gt;&lt;path d=&quot;M6.5 9C7.3 9 8 9.7 8 10.5V11.5C8 12.1 7.6 12.6 7.1 12.9L8 15H6.5L5.6 13H4.5V15H3V9H6.5M6.5 11.5V10.5H4.5V11.5H6.5M10.25 9H12.75L14.25 15H12.75L12.38 13.5H10.63L10.25 15H8.75L10.25 9M11 12H12L11.75 11H11.25L11 12M20 9H21.5L20 15H18.5L17.74 11.96L17 15H15.5L14 9H15.5L16.24 12L17 9H18.5L19.24 12L20 9Z&quot; /&gt;&lt;/svg&gt;.
        /// </summary>
        internal static string debug_raw {
            get {
                return ResourceManager.GetString("debug_raw", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string containing the Diagnostics tree-node icon SVG (a filled circle with a knocked-out pulse line).
        /// </summary>
        internal static string diagnostics {
            get {
                return ResourceManager.GetString("diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg width=&quot;10&quot; height=&quot;27&quot; viewBox=&quot;0 0 10 27&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;&lt;path class=&quot;{0}&quot; fill-rule=&quot;nonzero&quot; d=&quot;M10,0 L10,1.499 L2.99821951,1.5 C2.50520247,1.50042576 2.24655176,1.50681209 2.0460095,1.60899348 C1.85784741,1.70486685 1.70486685,1.85784741 1.60899348,2.0460095 C1.5,2.25992124 1.5,2.53994749 1.5,3.1 L1.5,7 L0,7 L0,3.1 C0,2.66678055 0.0022964717,2.52067108 0.0186058206,2.32105414 C0.0473168491,1.96964785 0.118563855,1.66710843 0.27248369,1.36502375 C0.512167127,0.894618518 0.8946185 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string status_bracket {
            get {
                return ResourceManager.GetString("status_bracket", resourceCulture);
            }
        }
    }
}
