//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollectionWizard.Client.Components.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataCollectionWizardPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataCollectionWizardPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataCollectionWizard.Client.Components.Localization.DataCollectionWizardPage", typeof(DataCollectionWizardPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add IO-Link Master.
        /// </summary>
        internal static string AddIoLinkMasterDialogHeader {
            get {
                return ResourceManager.GetString("AddIoLinkMasterDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add device.
        /// </summary>
        internal static string AddNewDevice {
            get {
                return ResourceManager.GetString("AddNewDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add VSE.
        /// </summary>
        internal static string AddVseDialogHeader {
            get {
                return ResourceManager.GetString("AddVseDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter alias.
        /// </summary>
        internal static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Alias.
        /// </summary>
        internal static string AliasDialogHeader {
            get {
                return ResourceManager.GetString("AliasDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration has changed.
        /// </summary>
        internal static string ClusterOutOfDateDialogHeader {
            get {
                return ResourceManager.GetString("ClusterOutOfDateDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somebody else saved a configuration. Your changes may override changes made by them. If that does not matter to you, you may ignore this warning, otherwise, please close the Data Collection Wizard and open it again to continue working on the latest configuration..
        /// </summary>
        internal static string ClusterOutOfDateDialogText {
            get {
                return ResourceManager.GetString("ClusterOutOfDateDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are approaching the recommended limit of enabled data points ({0} of {1})..
        /// </summary>
        internal static string DataPointLimitApproaching {
            get {
                return ResourceManager.GetString("DataPointLimitApproaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reached the recommended limit of enabled datapoints ({0} of {1}). Further enabling data points may result in system instability..
        /// </summary>
        internal static string DataPointLimitReached {
            get {
                return ResourceManager.GetString("DataPointLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all offline nodes.
        /// </summary>
        internal static string DeleteAllOfflineNodes {
            get {
                return ResourceManager.GetString("DeleteAllOfflineNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all offline nodes?.
        /// </summary>
        internal static string DeleteAllOfflineNodesDialogHeader {
            get {
                return ResourceManager.GetString("DeleteAllOfflineNodesDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete all currently offline nodes?.
        /// </summary>
        internal static string DeleteAllOfflineNodesDialogText {
            get {
                return ResourceManager.GetString("DeleteAllOfflineNodesDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete device?.
        /// </summary>
        internal static string DeleteDialogHeader {
            get {
                return ResourceManager.GetString("DeleteDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deleted device will only be applied after clicking &quot;Save&quot;..
        /// </summary>
        internal static string DeleteDialogText {
            get {
                return ResourceManager.GetString("DeleteDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete offline nodes.
        /// </summary>
        internal static string DeleteOfflineNodes {
            get {
                return ResourceManager.GetString("DeleteOfflineNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided address already exists..
        /// </summary>
        internal static string DeviceAddressNotUnique {
            get {
                return ResourceManager.GetString("DeviceAddressNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided address is not valid..
        /// </summary>
        internal static string InvalidDeviceAddress {
            get {
                return ResourceManager.GetString("InvalidDeviceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO-Link Master address.
        /// </summary>
        internal static string IoLinkMasterAddress {
            get {
                return ResourceManager.GetString("IoLinkMasterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO-Link Master.
        /// </summary>
        internal static string IoLinkMasterName {
            get {
                return ResourceManager.GetString("IoLinkMasterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning for IO-Link Master devices failed:.
        /// </summary>
        internal static string IoLinkScanErrorDuringScan {
            get {
                return ResourceManager.GetString("IoLinkScanErrorDuringScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter applied did not produce any results....
        /// </summary>
        internal static string IoLinkScanFilterNoResult {
            get {
                return ResourceManager.GetString("IoLinkScanFilterNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IO-Link Masters were found on the network....
        /// </summary>
        internal static string IoLinkScanNoResult {
            get {
                return ResourceManager.GetString("IoLinkScanNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Level.
        /// </summary>
        internal static string LogLevel {
            get {
                return ResourceManager.GetString("LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration of process values is generally supported for all data targets. For the moneo|cloud, this functionality will be enabled once the corresponding features are available. In the meantime, please use the configuration options provided directly in the moneo|cloud..
        /// </summary>
        internal static string MoneoDeactivatedTooltip {
            get {
                return ResourceManager.GetString("MoneoDeactivatedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display path.
        /// </summary>
        internal static string PathVisible {
            get {
                return ResourceManager.GetString("PathVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process data view.
        /// </summary>
        internal static string ProcessDataView {
            get {
                return ResourceManager.GetString("ProcessDataView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process value.
        /// </summary>
        internal static string ProcessValue {
            get {
                return ResourceManager.GetString("ProcessValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording settings.
        /// </summary>
        internal static string RecordingSettings {
            get {
                return ResourceManager.GetString("RecordingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive.
        /// </summary>
        internal static string Recursive {
            get {
                return ResourceManager.GetString("Recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan.
        /// </summary>
        internal static string Rescan {
            get {
                return ResourceManager.GetString("Rescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        internal static string Scheduler {
            get {
                return ResourceManager.GetString("Scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Compression Time.
        /// </summary>
        internal static string SetAllDatapointsCompression {
            get {
                return ResourceManager.GetString("SetAllDatapointsCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable All.
        /// </summary>
        internal static string SetAllDatapointsDisabled {
            get {
                return ResourceManager.GetString("SetAllDatapointsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable All.
        /// </summary>
        internal static string SetAllDatapointsEnabled {
            get {
                return ResourceManager.GetString("SetAllDatapointsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Raw Data Intervall.
        /// </summary>
        internal static string SetDebugRawDataGrid {
            get {
                return ResourceManager.GetString("SetDebugRawDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        internal static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show debug tooling.
        /// </summary>
        internal static string ShowDebugTooling {
            get {
                return ResourceManager.GetString("ShowDebugTooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for deployments.
        /// </summary>
        internal static string SpinnerMessageAwaitingCurrentDeployments {
            get {
                return ResourceManager.GetString("SpinnerMessageAwaitingCurrentDeployments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating IO-Link scan engine.
        /// </summary>
        internal static string SpinnerMessageCreatingScanEngine {
            get {
                return ResourceManager.GetString("SpinnerMessageCreatingScanEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying Dataflow.
        /// </summary>
        internal static string SpinnerMessageDeployingDataflow {
            get {
                return ResourceManager.GetString("SpinnerMessageDeployingDataflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Dataflow.
        /// </summary>
        internal static string SpinnerMessageGeneratingDataflow {
            get {
                return ResourceManager.GetString("SpinnerMessageGeneratingDataflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribing result output.
        /// </summary>
        internal static string SpinnerMessageSubscribingResultOutput {
            get {
                return ResourceManager.GetString("SpinnerMessageSubscribingResultOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggering DeviceTree scan.
        /// </summary>
        internal static string SpinnerMessageTriggeringDeviceScan {
            get {
                return ResourceManager.GetString("SpinnerMessageTriggeringDeviceScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggering IO-Link Master scan.
        /// </summary>
        internal static string SpinnerMessageTriggeringIoLinkScan {
            get {
                return ResourceManager.GetString("SpinnerMessageTriggeringIoLinkScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for scan result.
        /// </summary>
        internal static string SpinnerMessageWaitingForScanResult {
            get {
                return ResourceManager.GetString("SpinnerMessageWaitingForScanResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Collection Wizard.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes may be lost..
        /// </summary>
        internal static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSE address.
        /// </summary>
        internal static string VseAddress {
            get {
                return ResourceManager.GetString("VseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSE.
        /// </summary>
        internal static string VseName {
            get {
                return ResourceManager.GetString("VseName", resourceCulture);
            }
        }
    }
}
