//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollectionWizard.Client.Components.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataCollectionWizardPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataCollectionWizardPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataCollectionWizard.Client.Components.Localization.DataCollectionWizardPage", typeof(DataCollectionWizardPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to · {0} active.
        /// </summary>
        internal static string ActiveDatapointCount {
            get {
                return ResourceManager.GetString("ActiveDatapointCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add IO-Link Master.
        /// </summary>
        internal static string AddIoLinkMasterDialogHeader {
            get {
                return ResourceManager.GetString("AddIoLinkMasterDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add device.
        /// </summary>
        internal static string AddNewDevice {
            get {
                return ResourceManager.GetString("AddNewDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add VSE.
        /// </summary>
        internal static string AddVseDialogHeader {
            get {
                return ResourceManager.GetString("AddVseDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter alias.
        /// </summary>
        internal static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }

        internal static string AliasTreePreview {
            get {
                return ResourceManager.GetString("AliasTreePreview", resourceCulture);
            }
        }

        internal static string AliasEmptyHint {
            get {
                return ResourceManager.GetString("AliasEmptyHint", resourceCulture);
            }
        }

        internal static string AliasCharacterCount {
            get {
                return ResourceManager.GetString("AliasCharacterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit alias.
        /// </summary>
        internal static string AliasDialogHeader {
            get {
                return ResourceManager.GetString("AliasDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All clouds.
        /// </summary>
        internal static string AllClouds {
            get {
                return ResourceManager.GetString("AllClouds", resourceCulture);
            }
        }

        internal static string BulkSettings {
            get {
                return ResourceManager.GetString("BulkSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset to defaults.
        /// </summary>
        internal static string BulkReset {
            get {
                return ResourceManager.GetString("BulkReset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Turns recording off and puts interval, aggregation, schedule and triggers back to each cloud&apos;s own defaults.
        /// </summary>
        internal static string BulkResetHint {
            get {
                return ResourceManager.GetString("BulkResetHint", resourceCulture);
            }
        }

        internal static string BulkGroupProcessValues {
            get {
                return ResourceManager.GetString("BulkGroupProcessValues", resourceCulture);
            }
        }

        internal static string BulkGroupUncompressed {
            get {
                return ResourceManager.GetString("BulkGroupUncompressed", resourceCulture);
            }
        }

        internal static string BulkGroupRecordings {
            get {
                return ResourceManager.GetString("BulkGroupRecordings", resourceCulture);
            }
        }

        internal static string BulkFieldAggregationInterval {
            get {
                return ResourceManager.GetString("BulkFieldAggregationInterval", resourceCulture);
            }
        }

        internal static string BulkFieldAggregationFunction {
            get {
                return ResourceManager.GetString("BulkFieldAggregationFunction", resourceCulture);
            }
        }

        internal static string BulkFieldDays {
            get {
                return ResourceManager.GetString("BulkFieldDays", resourceCulture);
            }
        }

        internal static string BulkFieldTimesADay {
            get {
                return ResourceManager.GetString("BulkFieldTimesADay", resourceCulture);
            }
        }

        internal static string BulkGroupRawData {
            get {
                return ResourceManager.GetString("BulkGroupRawData", resourceCulture);
            }
        }

        internal static string BulkGroupTriggers {
            get {
                return ResourceManager.GetString("BulkGroupTriggers", resourceCulture);
            }
        }

        internal static string BulkFieldFrequency {
            get {
                return ResourceManager.GetString("BulkFieldFrequency", resourceCulture);
            }
        }

        internal static string BulkFieldDuration {
            get {
                return ResourceManager.GetString("BulkFieldDuration", resourceCulture);
            }
        }

        internal static string BulkFieldDelay {
            get {
                return ResourceManager.GetString("BulkFieldDelay", resourceCulture);
            }
        }

        internal static string BulkMixedValue {
            get {
                return ResourceManager.GetString("BulkMixedValue", resourceCulture);
            }
        }

        internal static string BulkRowCount {
            get {
                return ResourceManager.GetString("BulkRowCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} · {2} of them with raw data.
        /// </summary>
        internal static string BulkRowCountWithRawData {
            get {
                return ResourceManager.GetString("BulkRowCountWithRawData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} on · {1} off.
        /// </summary>
        internal static string BulkDistribution {
            get {
                return ResourceManager.GetString("BulkDistribution", resourceCulture);
            }
        }

        internal static string BulkNoSettings {
            get {
                return ResourceManager.GetString("BulkNoSettings", resourceCulture);
            }
        }

        internal static string BulkNothingApplicable {
            get {
                return ResourceManager.GetString("BulkNothingApplicable", resourceCulture);
            }
        }

        internal static string BulkTargetNotConfigurable {
            get {
                return ResourceManager.GetString("BulkTargetNotConfigurable", resourceCulture);
            }
        }

        internal static string BulkOnChangeLocked {
            get {
                return ResourceManager.GetString("BulkOnChangeLocked", resourceCulture);
            }
        }

        internal static string BulkReducedOptions {
            get {
                return ResourceManager.GetString("BulkReducedOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string BulkActivate {
            get {
                return ResourceManager.GetString("BulkActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        internal static string BulkDeactivate {
            get {
                return ResourceManager.GetString("BulkDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} selected.
        /// </summary>
        internal static string BulkSelectionCount {
            get {
                return ResourceManager.GetString("BulkSelectionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration has changed.
        /// </summary>
        internal static string ClusterOutOfDateDialogHeader {
            get {
                return ResourceManager.GetString("ClusterOutOfDateDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another participant saved a new configuration. Your changes may override changes made by them. If that does not matter to you, you may ignore this warning, otherwise, please close the Data Collection Wizard and open it again to continue working on the latest configuration..
        /// </summary>
        internal static string ClusterOutOfDateDialogText {
            get {
                return ResourceManager.GetString("ClusterOutOfDateDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approaching the recommended limit.
        /// </summary>
        internal static string DataPointLimitApproachingHint {
            get {
                return ResourceManager.GetString("DataPointLimitApproachingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recommended limit exceeded – may affect stability.
        /// </summary>
        internal static string DataPointLimitExceededHint {
            get {
                return ResourceManager.GetString("DataPointLimitExceededHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active data points.
        /// </summary>
        internal static string DataPointUsage {
            get {
                return ResourceManager.GetString("DataPointUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all offline nodes.
        /// </summary>
        internal static string DeleteAllOfflineNodes {
            get {
                return ResourceManager.GetString("DeleteAllOfflineNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all offline nodes?.
        /// </summary>
        internal static string DeleteAllOfflineNodesDialogHeader {
            get {
                return ResourceManager.GetString("DeleteAllOfflineNodesDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete all currently offline nodes?.
        /// </summary>
        internal static string DeleteAllOfflineNodesDialogText {
            get {
                return ResourceManager.GetString("DeleteAllOfflineNodesDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete device?.
        /// </summary>
        internal static string DeleteDialogHeader {
            get {
                return ResourceManager.GetString("DeleteDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deletion will only take effect after clicking &quot;Save&quot;..
        /// </summary>
        internal static string DeleteDialogText {
            get {
                return ResourceManager.GetString("DeleteDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete offline nodes.
        /// </summary>
        internal static string DeleteOfflineNodes {
            get {
                return ResourceManager.GetString("DeleteOfflineNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided address already exists..
        /// </summary>
        internal static string DeviceAddressNotUnique {
            get {
                return ResourceManager.GetString("DeviceAddressNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device scan failed:.
        /// </summary>
        internal static string DeviceScanError {
            get {
                return ResourceManager.GetString("DeviceScanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter applied did not produce any results....
        /// </summary>
        internal static string DeviceScanFilterNoResult {
            get {
                return ResourceManager.GetString("DeviceScanFilterNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No further devices were found on the network....
        /// </summary>
        internal static string DeviceScanNoResult {
            get {
                return ResourceManager.GetString("DeviceScanNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device requires authentication.
        /// </summary>
        internal static string DeviceScanRequiresAuthentication {
            get {
                return ResourceManager.GetString("DeviceScanRequiresAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        internal static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data volume.
        /// </summary>
        internal static string InfoDataVolume {
            get {
                return ResourceManager.GetString("InfoDataVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string InfoDay {
            get {
                return ResourceManager.GetString("InfoDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string InfoHour {
            get {
                return ResourceManager.GetString("InfoHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string InfoMonth {
            get {
                return ResourceManager.GetString("InfoMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not projectable.
        /// </summary>
        internal static string InfoNotProjectable {
            get {
                return ResourceManager.GetString("InfoNotProjectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depend on the actual signal / event — not part of the projection..
        /// </summary>
        internal static string InfoNotProjectableHint {
            get {
                return ResourceManager.GetString("InfoNotProjectableHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data points are only recorded on change.
        /// </summary>
        internal static string InfoOnChangeSuffix {
            get {
                return ResourceManager.GetString("InfoOnChangeSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection.
        /// </summary>
        internal static string InfoProjection {
            get {
                return ResourceManager.GetString("InfoProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raw-data recordings.
        /// </summary>
        internal static string InfoRawRecordingsSuffix {
            get {
                return ResourceManager.GetString("InfoRawRecordingsSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throughput.
        /// </summary>
        internal static string InfoThroughput {
            get {
                return ResourceManager.GetString("InfoThroughput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throughput share.
        /// </summary>
        internal static string InfoThroughputShare {
            get {
                return ResourceManager.GetString("InfoThroughputShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from pending changes.
        /// </summary>
        internal static string InfoUnsavedChangesSuffix {
            get {
                return ResourceManager.GetString("InfoUnsavedChangesSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string InfoWeek {
            get {
                return ResourceManager.GetString("InfoWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided address is not valid..
        /// </summary>
        internal static string InvalidDeviceAddress {
            get {
                return ResourceManager.GetString("InvalidDeviceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials for the selected masters.
        /// </summary>
        internal static string IoLinkCredentialStepHint {
            get {
                return ResourceManager.GetString("IoLinkCredentialStepHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO-Link Master address.
        /// </summary>
        internal static string IoLinkMasterAddress {
            get {
                return ResourceManager.GetString("IoLinkMasterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. 192.168.178.96.
        /// </summary>
        internal static string IoLinkMasterAddressExample {
            get {
                return ResourceManager.GetString("IoLinkMasterAddressExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string IoLinkMasterAuthentication {
            get {
                return ResourceManager.GetString("IoLinkMasterAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string IoLinkMasterConnection {
            get {
                return ResourceManager.GetString("IoLinkMasterConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network address of the IO-Link master.
        /// </summary>
        internal static string IoLinkMasterConnectionHint {
            get {
                return ResourceManager.GetString("IoLinkMasterConnectionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only required for IO-Link Masters that use authentication.
        /// </summary>
        internal static string IoLinkMasterCredentialsHint {
            get {
                return ResourceManager.GetString("IoLinkMasterCredentialsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO-Link Master.
        /// </summary>
        internal static string IoLinkMasterName {
            get {
                return ResourceManager.GetString("IoLinkMasterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string IoLinkMasterPassword {
            get {
                return ResourceManager.GetString("IoLinkMasterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string IoLinkMasterUsername {
            get {
                return ResourceManager.GetString("IoLinkMasterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the same credentials for all.
        /// </summary>
        internal static string IoLinkUseSameCredentialsForAll {
            get {
                return ResourceManager.GetString("IoLinkUseSameCredentialsForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log level.
        /// </summary>
        internal static string LogLevel {
            get {
                return ResourceManager.GetString("LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration of process values is generally supported for all data targets. For the moneo|cloud, this functionality will be enabled once the corresponding features are available. In the meantime, please use the configuration options provided directly in the moneo|cloud..
        /// </summary>
        internal static string MoneoDeactivatedTooltip {
            get {
                return ResourceManager.GetString("MoneoDeactivatedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not saved.
        /// </summary>
        internal static string NotSaved {
            get {
                return ResourceManager.GetString("NotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display path.
        
        /// <summary>
        ///   Looks up a localized string similar to Process data view.
        /// </summary>
        internal static string ProcessDataView {
            get {
                return ResourceManager.GetString("ProcessDataView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process value.
        /// </summary>
        internal static string ProcessValue {
            get {
                return ResourceManager.GetString("ProcessValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording settings.
        /// </summary>
        internal static string RecordingSettings {
            get {
                return ResourceManager.GetString("RecordingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive.
        /// </summary>
        internal static string Recursive {
            get {
                return ResourceManager.GetString("Recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan.
        /// </summary>
        internal static string Rescan {
            get {
                return ResourceManager.GetString("Rescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        internal static string Scheduler {
            get {
                return ResourceManager.GetString("Scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set compression time.
        /// </summary>
        internal static string SetAllDatapointsCompression {
            get {
                return ResourceManager.GetString("SetAllDatapointsCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable all.
        /// </summary>
        internal static string SetAllDatapointsDisabled {
            get {
                return ResourceManager.GetString("SetAllDatapointsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable all.
        /// </summary>
        internal static string SetAllDatapointsEnabled {
            get {
                return ResourceManager.GetString("SetAllDatapointsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug raw data interval.
        /// </summary>
        internal static string SetDebugRawDataGrid {
            get {
                return ResourceManager.GetString("SetDebugRawDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        internal static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show debug tooling.
        /// </summary>
        internal static string ShowDebugTooling {
            get {
                return ResourceManager.GetString("ShowDebugTooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for deployments.
        /// </summary>
        internal static string SpinnerMessageAwaitingCurrentDeployments {
            get {
                return ResourceManager.GetString("SpinnerMessageAwaitingCurrentDeployments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating scan engine.
        /// </summary>
        internal static string SpinnerMessageCreatingScanEngine {
            get {
                return ResourceManager.GetString("SpinnerMessageCreatingScanEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying Dataflow.
        /// </summary>
        internal static string SpinnerMessageDeployingDataflow {
            get {
                return ResourceManager.GetString("SpinnerMessageDeployingDataflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Dataflow.
        /// </summary>
        internal static string SpinnerMessageGeneratingDataflow {
            get {
                return ResourceManager.GetString("SpinnerMessageGeneratingDataflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribing result output.
        /// </summary>
        internal static string SpinnerMessageSubscribingResultOutput {
            get {
                return ResourceManager.GetString("SpinnerMessageSubscribingResultOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggering device scan.
        /// </summary>
        internal static string SpinnerMessageTriggeringDeviceScan {
            get {
                return ResourceManager.GetString("SpinnerMessageTriggeringDeviceScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggering DeviceTree scan.
        /// </summary>
        internal static string SpinnerMessageTriggeringDeviceTreeScan {
            get {
                return ResourceManager.GetString("SpinnerMessageTriggeringDeviceTreeScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for scan result.
        /// </summary>
        internal static string SpinnerMessageWaitingForScanResult {
            get {
                return ResourceManager.GetString("SpinnerMessageWaitingForScanResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Collection Wizard.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes may be lost..
        /// </summary>
        internal static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the changes before leaving?.
        /// </summary>
        internal static string UnsavedChangesPrompt {
            get {
                return ResourceManager.GetString("UnsavedChangesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes.
        /// </summary>
        internal static string UnsavedChangesTitle {
            get {
                return ResourceManager.GetString("UnsavedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSE address.
        /// </summary>
        internal static string VseAddress {
            get {
                return ResourceManager.GetString("VseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. 192.168.178.100.
        /// </summary>
        internal static string VseAddressExample {
            get {
                return ResourceManager.GetString("VseAddressExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network address of the VSE device.
        /// </summary>
        internal static string VseConnectionHint {
            get {
                return ResourceManager.GetString("VseConnectionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSE.
        /// </summary>
        internal static string VseName {
            get {
                return ResourceManager.GetString("VseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string WizardNext {
            get {
                return ResourceManager.GetString("WizardNext", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select device.
        /// </summary>
        internal static string WizardStepDeviceSelection {
            get {
                return ResourceManager.GetString("WizardStepDeviceSelection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string WizardStepCredentials {
            get {
                return ResourceManager.GetString("WizardStepCredentials", resourceCulture);
            }
        }
    }
}
