//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollectionWizard.Client.Components.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DeviceTreeTooltip {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeviceTreeTooltip() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataCollectionWizard.Client.Components.Localization.DeviceTreeTooltip", typeof(DeviceTreeTooltip).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newly added.
        /// </summary>
        internal static string DeviceStatusNewlyCreated {
            get {
                return ResourceManager.GetString("DeviceStatusNewlyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not supported.
        /// </summary>
        internal static string DeviceStatusNotSupported {
            get {
                return ResourceManager.GetString("DeviceStatusNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to device is offline.
        /// </summary>
        internal static string DeviceStatusOffline {
            get {
                return ResourceManager.GetString("DeviceStatusOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown device.
        /// </summary>
        internal static string DeviceStatusUnknown {
            get {
                return ResourceManager.GetString("DeviceStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        internal static string InfoPropertyAlias {
            get {
                return ResourceManager.GetString("InfoPropertyAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App specific tag.
        /// </summary>
        internal static string InfoPropertyApplicationSpecificTag {
            get {
                return ResourceManager.GetString("InfoPropertyApplicationSpecificTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string InfoPropertyDescription {
            get {
                return ResourceManager.GetString("InfoPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device family.
        /// </summary>
        internal static string InfoPropertyDeviceFamily {
            get {
                return ResourceManager.GetString("InfoPropertyDeviceFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID.
        /// </summary>
        internal static string InfoPropertyDeviceId {
            get {
                return ResourceManager.GetString("InfoPropertyDeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware revision.
        /// </summary>
        internal static string InfoPropertyHardwareRevision {
            get {
                return ResourceManager.GetString("InfoPropertyHardwareRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input type.
        /// </summary>
        internal static string InfoPropertyInputType {
            get {
                return ResourceManager.GetString("InfoPropertyInputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is writeable.
        /// </summary>
        internal static string InfoPropertyIsWritable {
            get {
                return ResourceManager.GetString("InfoPropertyIsWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC address.
        /// </summary>
        internal static string InfoPropertyMacAddress {
            get {
                return ResourceManager.GetString("InfoPropertyMacAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string InfoPropertyManufacturer {
            get {
                return ResourceManager.GetString("InfoPropertyManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer ID.
        /// </summary>
        internal static string InfoPropertyManufacturerId {
            get {
                return ResourceManager.GetString("InfoPropertyManufacturerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string InfoPropertyPath {
            get {
                return ResourceManager.GetString("InfoPropertyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product code.
        /// </summary>
        internal static string InfoPropertyProductCode {
            get {
                return ResourceManager.GetString("InfoPropertyProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        internal static string InfoPropertyProductName {
            get {
                return ResourceManager.GetString("InfoPropertyProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor type.
        /// </summary>
        internal static string InfoPropertySensorType {
            get {
                return ResourceManager.GetString("InfoPropertySensorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        internal static string InfoPropertySerialNumber {
            get {
                return ResourceManager.GetString("InfoPropertySerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software revision.
        /// </summary>
        internal static string InfoPropertySoftwareRevision {
            get {
                return ResourceManager.GetString("InfoPropertySoftwareRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string InfoPropertyType {
            get {
                return ResourceManager.GetString("InfoPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string InfoPropertyUnit {
            get {
                return ResourceManager.GetString("InfoPropertyUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor ID.
        /// </summary>
        internal static string InfoPropertyVendorId {
            get {
                return ResourceManager.GetString("InfoPropertyVendorId", resourceCulture);
            }
        }
    }
}
