//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollectionWizard.Client.Components.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LiveViewPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LiveViewPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataCollectionWizard.Client.Components.Localization.LiveViewPage", typeof(LiveViewPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration has changed.
        /// </summary>
        internal static string ClusterOutOfDateDialogHeader {
            get {
                return ResourceManager.GetString("ClusterOutOfDateDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live process data may not be available now since the DeviceTree you are looking at is out of date..
        /// </summary>
        internal static string ClusterOutOfDateDialogText {
            get {
                return ResourceManager.GetString("ClusterOutOfDateDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated.
        /// </summary>
        internal static string LastChanged {
            get {
                return ResourceManager.GetString("LastChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This column is updated only if the value has actually changed..
        /// </summary>
        internal static string LastChangedHint {
            get {
                return ResourceManager.GetString("LastChangedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Cluster is not Active.
        /// </summary>
        internal static string LatestClusterNotRunningDialogHeader {
            get {
                return ResourceManager.GetString("LatestClusterNotRunningDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live process data may not be able to be displayed. If that is the case, an error may have occured during the deployment. Please use the Cluster Manager to check if the latest cluster can be started. If not, contact an administrator..
        /// </summary>
        internal static string LatestClusterNotRunningDialogText {
            get {
                return ResourceManager.GetString("LatestClusterNotRunningDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live process data view.
        /// </summary>
        internal static string LiveView {
            get {
                return ResourceManager.GetString("LiveView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display path.
        /// </summary>
        internal static string PathVisible {
            get {
                return ResourceManager.GetString("PathVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process value.
        /// </summary>
        internal static string ProcessValue {
            get {
                return ResourceManager.GetString("ProcessValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive.
        /// </summary>
        internal static string Recursive {
            get {
                return ResourceManager.GetString("Recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan.
        /// </summary>
        internal static string Rescan {
            get {
                return ResourceManager.GetString("Rescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live View.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
