<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
        <!-- General -->
        <TargetFramework>net10.0</TargetFramework>
        <RuntimeIdentifiers Condition="$(MSBuildProjectDirectory.Contains('src'))">linux-x64;linux-arm64;win-x64</RuntimeIdentifiers>
        <ImplicitUsings>enable</ImplicitUsings>
        <Description>-</Description>
        <Product>ViciOne</Product>
        <Company>ViciOne open automation gmbh</Company>
        <Year>$([System.DateTime]::Now.Year)</Year>
        <Copyright>Copyright © $(Company) $(Year)</Copyright>
        <NeutralLanguage>en</NeutralLanguage>
        <SatelliteResourceLanguages>en;de</SatelliteResourceLanguages>
        <!-- Code quality -->
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <NoWarn>$(NoWarn);EnableGenerateDocumentationFile</NoWarn> <!-- Workaround for https://github.com/dotnet/roslyn/issues/41640 -->
        <!-- NuGet lock file -->
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <RestoreLockedMode Condition="'$(CI)' == 'true'">true</RestoreLockedMode>
        <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
        <DisableImplicitLibraryPacksFolder>true</DisableImplicitLibraryPacksFolder>
        <NuGetAuditMode>all</NuGetAuditMode>
    </PropertyGroup>

    <!-- NuGet packages -->
    <PropertyGroup>
        <!-- https://docs.microsoft.com/de-de/nuget/reference/msbuild-targets -->
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
        <PackageProjectUrl>https://gitlab.com/vicione-oss/vicione/suite-apps/data-collection-wizard</PackageProjectUrl>
        <Authors>$(Company)</Authors>
    </PropertyGroup>
    
    <ItemGroup>
        <None Include="$(MsBuildThisFileDirectory)\LICENSE.txt" Pack="true" PackagePath="" />
    </ItemGroup>

    <!-- Configure xunit runner for test projects -->
    <ItemGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
        <Content Include="$(MSBuildThisFileDirectory)/tests/xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <!-- Don't publish test projects -->
    <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('Tests')) And $(MSBuildProjectDirectory.Contains('tests'))">
        <NoWarn>$(NoWarn);IDE1006</NoWarn>
        <NoWarn>$(NoWarn);VO2006</NoWarn>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <IsPublishable>true</IsPublishable>
        <!-- Microsoft Testing Platform command line experience -->
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    </PropertyGroup>

    <ItemGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="NSubstitute.Analyzers.CSharp">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>        
        <PackageReference Include="ViciOne.Suite.Sdk.Testing" />
        <PackageReference Include="xunit.v3.mtp-v2" />

        <!-- Global usings for all test projects -->
        <Using Include="Xunit" />
        <Using Include="NSubstitute" />
    </ItemGroup>

</Project>
