<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
        <!-- General -->
        <TargetFramework>net10.0</TargetFramework>
        <RuntimeIdentifiers Condition="$(MSBuildProjectDirectory.Contains('src'))">linux-x64;linux-arm64;win-x64</RuntimeIdentifiers>
        <ImplicitUsings>enable</ImplicitUsings>
        <Description>-</Description>
        <Product>ViciOne</Product>
        <Company>ifm software gmbh</Company>
        <Year>$([System.DateTime]::Now.Year)</Year>
        <Copyright>Copyright © $(Company) $(Year)</Copyright>
        <NeutralLanguage>en</NeutralLanguage>
        <SatelliteResourceLanguages>en;de</SatelliteResourceLanguages>
        <!-- Code quality -->
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <NoWarn>$(NoWarn);EnableGenerateDocumentationFile</NoWarn> <!-- Workaround for https://github.com/dotnet/roslyn/issues/41640 -->
        <!-- NuGet lock file -->
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <RestoreLockedMode Condition="'$(CI)' == 'true'">true</RestoreLockedMode>
        <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
        <DisableImplicitLibraryPacksFolder>true</DisableImplicitLibraryPacksFolder>
        <NuGetAuditMode>all</NuGetAuditMode>
    </PropertyGroup>

    <!-- NuGet packages -->
    <PropertyGroup>
        <!-- https://docs.microsoft.com/de-de/nuget/reference/msbuild-targets -->
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
        <PackageProjectUrl>https://gitlab.com/vicione-oss/vicione/suite-apps/data-collection-wizard</PackageProjectUrl>
        <Authors>$(Company)</Authors>
    </PropertyGroup>
    
    <ItemGroup>
        <None Include="$(MsBuildThisFileDirectory)\LICENSE.txt" Pack="true" PackagePath="" />
    </ItemGroup>

    <!-- Don't publish test projects -->
    <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('Tests')) Or $(MSBuildProjectDirectory.Contains('tests'))">
        <IsPackable>false</IsPackable>
        <IsPublishable>false</IsPublishable>
        <NoWarn>$(NoWarn);IDE1006</NoWarn>
        <NoWarn>$(NoWarn);VO2006</NoWarn>
        <RunSettingsFilePath>$(MsBuildThisFileDirectory)\tests.runsettings</RunSettingsFilePath>
    </PropertyGroup>

    <!-- Remove SDK files from backend -->
    <Target Name="EnsureSdkGetsRemovedIssue" AfterTargets="GenerateDepsFile" Condition="'$(Configuration)' == 'Release' And $(ProjectName.EndsWith('.Backend'))">
        <ItemGroup>
            <FilesToClean Include="$(TargetDir)ViciOne.Suite.Sdk.*" />
        </ItemGroup>
        <Delete Files="@(FilesToClean)"></Delete>
    </Target>
</Project>
