// <auto-generated />
using System;
using DataCollectionWizard.Backend.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataCollectionWizard.Backend.Migrations.DataCollectionWizardDbContext.Postgres
{
    [DbContext(typeof(DataCollectionWizardAttributeDbContextPostgres))]
    [Migration("20240716101202_DataCollectionWizardInit")]
    partial class DataCollectionWizardInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("data-collection-wizard")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataCollectionWizard.Backend.DbContext.DeviceTreeDbModel", b =>
                {
                    b.Property<string>("DeviceAddress")
                        .HasColumnType("text");

                    b.Property<string>("DeviceTreeJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeviceAddress");

                    b.ToTable("Devices", "data-collection-wizard");
                });

            modelBuilder.Entity("DataCollectionWizard.Internal.Contracts.DeviceConnectorIds", b =>
                {
                    b.Property<string>("DeviceAddress")
                        .HasColumnType("text");

                    b.Property<Guid>("TriggerInput")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceTreeOutput")
                        .HasColumnType("uuid");

                    b.HasKey("DeviceAddress", "TriggerInput", "DeviceTreeOutput");

                    b.ToTable("DeviceConnectorIds", "data-collection-wizard");
                });
#pragma warning restore 612, 618
        }
    }
}
