<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>ViciOne.Suite.DataCollectionWizard.Client.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Semver" />
    <PackageReference Include="ViciOne.Core.Dataflow.DataModel.Generation" />
    <PackageReference Include="ViciOne.Ui.TreeEditor" />    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DataCollectionWizard.Client\DataCollectionWizard.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
