<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>ViciOne.Suite.DataCollectionWizard.Internal</AssemblyName>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="ViciOne.Cluster.Builder" />
    <PackageReference Include="ViciOne.DeviceTree.Contracts" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ViciOne.Suite.ClusterManagement.Public" />
    <PackageReference Include="ViciOne.Suite.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ViciOne.Suite.DataCollectionWizard.Internal.Tests" />
    <InternalsVisibleTo Include="ViciOne.Suite.DataCollectionWizard.Client.Tests" />
    <InternalsVisibleTo Include="ViciOne.Suite.DataCollectionWizard.Backend.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataCollectionWizard.Public\DataCollectionWizard.Public.csproj" />
  </ItemGroup>
  
</Project>
