<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>ViciOne.Suite.DataCollectionWizard.Backend</AssemblyName>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
  </PropertyGroup>

  <ItemGroup>    
    <PackageReference Include="ViciOne.Suite.Sdk.Backend" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ViciOne.Suite.DataCollectionWizard.Backend.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataCollectionWizard.Internal\DataCollectionWizard.Internal.csproj" />
  </ItemGroup>

</Project>
