<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AssemblyName>ViciOne.Suite.DataCollectionWizard.Client</AssemblyName>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
    <CompressionEnabled>false</CompressionEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.SassCompiler" PrivateAssets="all" />
    <PackageReference Include="ViciOne.Suite.Sdk.Client" />
    <PackageReference Include="ViciOne.Ui.Design">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="ViciOne.Ui.Blazor.Components" />
    <PackageReference Include="ViciOne.Ui.MonochromeIcons.Components" />
    <PackageReference Include="ViciOne.Ui.Shared.Dx" />
    <PackageReference Include="ViciOne.Ui.TreeEditor" />
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ViciOne.Suite.DataCollectionWizard.Client.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <!-- Prevent Microsoft.NET.Sdk.Razor from copying unnecessary file -->
  <ItemGroup>
    <Content Update="Components\LiveGrid\GridCells\DeviceIdentifierCell.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="sasscompiler.json" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
    <Content Update="package*.json" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Components\Localization\DeviceTreeTooltip.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DeviceTreeTooltip.resx</DependentUpon>
    </Compile>
    <Compile Update="Components\Localization\LiveViewPage.Designer.cs">
      <DependentUpon>LiveViewPage.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Components\Localization\DataCollectionWizardPage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DataCollectionWizardPage.resx</DependentUpon>
    </Compile>
    <Compile Update="Components\NavTiles\Localization\DataCollectionWizardNavTile.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DataCollectionWizardNavTile.resx</DependentUpon>
    </Compile>
    <Compile Update="Components\NavTiles\Localization\LiveViewNavTile.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LiveViewNavTile.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\SvgIcons.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SvgIcons.resx</DependentUpon>
    </Compile>
    <Compile Update="Services\Localization\DeviceTreeAdapter.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DeviceTreeAdapter.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Components\Localization\DeviceTreeTooltip.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>DeviceTreeTooltip.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Components\Localization\LiveViewPage.resx">
      <LastGenOutput>LiveViewPage.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Components\Localization\DataCollectionWizardPage.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>DataCollectionWizardPage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Components\NavTiles\Localization\DataCollectionWizardNavTile.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>DataCollectionWizardNavTile.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Components\NavTiles\Localization\LiveViewNavTile.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>LiveViewNavTile.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\SvgIcons.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SvgIcons.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Services\Localization\DeviceTreeAdapter.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>DeviceTreeAdapter.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <UpToDateCheckInput Remove="Components\DataCollectionWizardPage - Copy.razor.scss" />
  </ItemGroup>
  <ItemGroup>
    <UpToDateCheckInput Remove="Components\LiveGrid\DataCollectionWizardGrid.razor.scss" />
  </ItemGroup>
  <ItemGroup>
    <UpToDateCheckInput Remove="Components\LiveGrid\GridCells\DeviceIdentifierCell.razor.scss" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DataCollectionWizard.Internal\DataCollectionWizard.Internal.csproj" />
  </ItemGroup>

  <Target Name="ConfigureDesignTargets" BeforeTargets="BeforeDesignTargets">
    <PropertyGroup>
      <ColorsScssOutputFolder>$(MSBuildProjectDirectory)/Styles/design/colors</ColorsScssOutputFolder>
    </PropertyGroup>
  </Target>
</Project>
